# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Kurly_mock' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Kurly_mock
  pod 'Alamofire', '~> 5.2'
  pod 'AlamofireNetworkActivityIndicator'
  pod 'SnapKit'
  pod 'DLRadioButton', '~> 1.4'
  pod 'Kingfisher', '~> 6.0'
end
